### ISSUE TITLE
MY HEALTH¬!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Cheesey-boi** [lilybugged/bunnythm#2]
using health potions does not appear to be capped at your 'max health' and so can just keep raising your hp.
![Capture](https://user-images.githubusercontent.com/81922496/113517270-cb095c80-9576-11eb-897b-fc337b7c4362.PNG)

**Comment by Cheesey-boi** [comment]
Re-logging does not reset this value. Just checked.

**Comment by lilybugged** [comment]
This issue has been fixed server-side and is now live.
