### ISSUE TITLE
Move this license to the metadata inspector plugin

### ISSUE THREAD

**Issue by waleed177** [lilybugged/bunnythm#3]
![image](https://user-images.githubusercontent.com/33373452/114232127-101cfc80-9984-11eb-85b6-3c38eff875f5.png)

Move this license to the metadata inspector plugin.

**Comment by lilybugged** [comment]
Fixed in this commit https://github.com/lilybugged/bunnythm/commit/f96c6b9bbbd7f0333a977c346519d76acfb14a47#diff-bbbd1cd7877662dc3d444e9c6ef5e254832d5a00ee269121bd1393e260bc8772
